# Generated by Django 5.0.2 on 2024-03-29 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseID', models.AutoField(primary_key=True, serialize=False)),
                ('SubjectCode', models.CharField(max_length=255)),
                ('SubjectDescription', models.CharField(max_length=255)),
                ('Section', models.CharField(max_length=255)),
                ('Professor', models.CharField(max_length=255)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
