# Generated by Django 5.0.2 on 2024-03-29 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('was', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('ScheduleID', models.AutoField(primary_key=True, serialize=False)),
                ('DayOfWeek', models.CharField(max_length=255)),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='was.course')),
            ],
        ),
    ]
