# Generated by Django 5.0.2 on 2024-03-29 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('was', '0002_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='UserID',
            new_name='CourseID',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('TaskID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('Deadline', models.DateTimeField()),
                ('Type', models.CharField(max_length=255)),
                ('Score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('Status', models.CharField(max_length=255)),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='was.course')),
            ],
        ),
    ]
