# Generated by Django 5.0.2 on 2024-03-29 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('was', '0003_rename_userid_schedule_courseid_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Score',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('GradeID', models.AutoField(primary_key=True, serialize=False)),
                ('MidtermGrade', models.DecimalField(decimal_places=1, max_digits=11)),
                ('FinalGrade', models.DecimalField(decimal_places=1, max_digits=11)),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='was.course')),
            ],
        ),
    ]
