# Generated by Django 5.0.2 on 2024-03-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('was', '0004_alter_task_score_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='FinalGrade',
            field=models.DecimalField(decimal_places=1, max_digits=1),
        ),
        migrations.AlterField(
            model_name='grade',
            name='MidtermGrade',
            field=models.DecimalField(decimal_places=1, max_digits=1),
        ),
    ]
