# Generated by Django 5.0.3 on 2024-04-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('was', '0007_remove_task_status_task_iscomplete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Score',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=11),
        ),
    ]
