# Generated by Django 5.0.2 on 2024-04-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('was', '0010_task_score_over'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='FinalGrade',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='grade',
            name='MidtermGrade',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
