# Generated by Django 5.0.2 on 2024-04-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('was', '0012_alter_grade_finalgrade_alter_grade_midtermgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='FinalGrade',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='grade',
            name='MidtermGrade',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=3),
        ),
    ]
