# Generated by Django 5.0.2 on 2024-04-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('was', '0013_alter_grade_finalgrade_alter_grade_midtermgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='CourseImage',
            field=models.ImageField(default='default/courseplaceholder.png', upload_to='uploaded/course/'),
        ),
    ]
