# Generated by Django 5.0.2 on 2024-04-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('was', '0014_course_courseimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='CourseImage',
            field=models.ImageField(default='default/courseplaceholder.png', upload_to='uploaded/'),
        ),
    ]
