# Generated by Django 5.0.2 on 2024-05-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('was', '0015_alter_course_courseimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dateCompleted',
            field=models.DateTimeField(null=True),
        ),
    ]
